name: symparsec
version: 1.0.1
synopsis: Type level string parser combinators
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
category: Types, Data
license: MIT
license-file: LICENSE
tested-with:
- GHC==9.8
- GHC==9.6

github: raehik/symparsec
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

# raehik's extensions (GHC 9.2; last updated: 2022-10-09)
language: GHC2021
default-extensions:
# syntax that should be default
- LambdaCase
- NoStarIsType

## deriving-related
- DerivingVia # implies DerivingStrategies
- DeriveAnyClass

# features that should be default
- GADTs
- RoleAnnotations

# other features
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash

# useful extensions to know about, but which should be specified on-demand
#
# UndecidableInstances:
#   required for type class wizardry
#   generally only enable if you were expecting to & compilation fails without
# AllowAmbiguousTypes:
#   often goes hand in hand with TypeApplications-heavy code
#   enabling on demand brings attention to the sort of functions to expect
# StarIsType:
#   may need to enable if you're working with old code that uses `Int :: *`

ghc-options:
- -Wall

# omitting ticks is good; see https://gitlab.haskell.org/ghc/ghc/-/issues/20531
# (off by default since GHC 9.4)
- -Wno-unticked-promoted-constructors

dependencies:
- base >= 4.18 && < 5
- defun-core ^>= 0.1
- singleraeh ^>= 0.4.0
- type-level-show ^>= 0.3.0

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
    - symparsec
    - type-spec ^>= 0.4.0.0
